baseURL = "https://Asif.github.io/asiftanvir.github.io/"
title = "Asif Blog"
author = "Asif"
copyright = "asiftanvir"
paginate = 10
languageCode = "en"
theme = "hugo-theme-tailwind"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "wall.jpg"

  [params.footer]
    since = 2023
    poweredby = true

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pageRef = "/posts"
    weight = 0

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
